/**
 * Generates `assets/tokens.css` from the TypeScript token source.
 *
 * The TS objects in `src/` are the single source of truth; this file exists so
 * the web app can consume the same values as CSS custom properties without a
 * JS round-trip. Run `npm run build --workspace=@promoted/brand` (which calls
 * this after tsc) whenever tokens change, and commit the result.
 */
import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const { cssVariables, fontFamily, elevation, feed } = await import(
  resolve(here, '../dist/index.js')
);

const block = (selector, vars, indent = '  ') =>
  `${selector} {\n${Object.entries(vars)
    .map(([k, v]) => `${indent}${k}: ${v};`)
    .join('\n')}\n}`;

const shared = {
  '--pr-font-display': fontFamily.display,
  '--pr-font-text': fontFamily.text,
  '--pr-font-mono': fontFamily.mono,
  '--pr-shadow-card': elevation.card,
  '--pr-shadow-sheet': elevation.sheet,
  '--pr-shadow-accent-glow': elevation.accentGlow,
  '--pr-feed-max-width': `${feed.maxWidthPx}px`,
  '--pr-feed-action-rail': `${feed.actionRailHeight}px`,
};

const css = `/* AUTO-GENERATED by packages/brand/scripts/gen-tokens.mjs — do not edit by hand. */
/* Source of truth: packages/brand/src/*.ts */

${block(':root', { ...cssVariables('light'), ...shared })}

/* Explicit opt-in wins in both directions. */
${block(":root[data-theme='dark']", cssVariables('dark'))}

/* System preference, unless the user explicitly chose light. */
@media (prefers-color-scheme: dark) {
${block("  :root:not([data-theme='light'])", cssVariables('dark'), '    ')}
}

/* The lesson feed is always dark, in every theme. It is a cinema, not a page. */
${block("[data-surface='feed']", cssVariables('dark'))}
`;

mkdirSync(resolve(here, '../assets'), { recursive: true });
writeFileSync(resolve(here, '../assets/tokens.css'), css, 'utf8');
console.log('wrote packages/brand/assets/tokens.css');
