#!/usr/bin/env python3
"""
Vectorise the New Manager Success mark from the source raster.

The supplied artwork is a brush-painted PNG on a black field. Rather than
redraw it — a hand-approximated brush always reads worse than the real thing —
this splits the image into its white (letterform) and blue (arrow) channels,
traces each with potrace, and writes the path data to
`packages/brand/src/mark.ts`, which both the web and native components import.

    python3 packages/brand/scripts/trace-mark.py
    npm run build --workspace=@nms/brand
    node packages/brand/scripts/gen-icons.mjs

Requires: potrace, Pillow, numpy.
    apt-get install -y potrace && pip install pillow numpy

Re-run this whenever the source artwork changes. If a true vector master
(.ai/.eps/.svg) ever arrives, retire this script and use that instead.
"""
import json
import re
import subprocess
import sys
import tempfile
from pathlib import Path

try:
    import numpy as np
    from PIL import Image
except ImportError:  # pragma: no cover
    sys.exit("Needs Pillow and numpy:  pip install pillow numpy")

BRAND = Path(__file__).resolve().parent.parent
SOURCE = BRAND / "assets" / "source" / "mark.png"
OUT_TS = BRAND / "src" / "mark.ts"

# Padding around the inked bounds, in source pixels.
PAD = 6
# potrace: keep specks down to 1px — the dry-brush flecks are the character,
# not noise, so this is deliberately as low as it goes.
TURDSIZE = "1"


def masks(rgb: "np.ndarray"):
    """Split the artwork into (letterform, arrow) boolean masks.

    Thresholds are deliberately loose. The source is a re-compressed raster
    with a soft glow around the strokes, so a strict cut leaves the edges
    ragged; potrace smooths what is left.
    """
    r, g, b = rgb[:, :, 0], rgb[:, :, 1], rgb[:, :, 2]
    luminance = 0.299 * r + 0.587 * g + 0.114 * b

    arrow = (b > 90) & ((b - r) > 45) & ((b - g) > 25)
    letter = (
        (luminance > 105)
        & (~arrow)
        & (np.abs(r - g) < 45)
        & (np.abs(g - b) < 55)
    )
    return letter, arrow


def trace(mask, tmp: Path, name: str) -> tuple[str, str]:
    """Run potrace over one mask; return (path data, potrace's transform)."""
    pbm = tmp / f"{name}.pbm"
    svg = tmp / f"{name}.svg"
    # In PBM, black is ink.
    Image.fromarray(np.where(mask, 0, 255).astype(np.uint8)).convert("1").save(pbm)
    subprocess.run(
        ["potrace", "-b", "svg", "--turdsize", TURDSIZE,
         "--alphamax", "1.0", "--opttolerance", "0.3", "-o", str(svg), str(pbm)],
        check=True,
    )
    text = svg.read_text()
    group = re.search(r"<g([^>]*)>\s*<path([^>]*)d=\"([\s\S]*?)\"", text)
    if not group:
        sys.exit(f"potrace produced no path for {name}")
    data = re.sub(r"\s+", " ", group.group(3)).strip()
    transform = re.search(r'transform="([^"]+)"', group.group(1))
    return data, (transform.group(1) if transform else "")


def sampled_blue(rgb, arrow) -> str:
    """Median of the strongest blue pixels — the brand blue, from the source."""
    px = rgb[arrow]
    lum = 0.299 * px[:, 0] + 0.587 * px[:, 1] + 0.114 * px[:, 2]
    core = px[lum >= np.percentile(lum, 55)]
    return "#%02X%02X%02X" % tuple(np.median(core, axis=0).astype(int))


def main() -> None:
    if not SOURCE.exists():
        sys.exit(f"No source artwork at {SOURCE}")

    rgb = np.asarray(Image.open(SOURCE).convert("RGB")).astype(np.int16)
    letter, arrow = masks(rgb)

    ys, xs = np.nonzero(letter | arrow)
    x0, x1 = int(xs.min()) - PAD, int(xs.max()) + PAD
    y0, y1 = int(ys.min()) - PAD, int(ys.max()) + PAD
    crop = lambda m: m[y0:y1 + 1, x0:x1 + 1]  # noqa: E731
    width, height = x1 - x0 + 1, y1 - y0 + 1

    with tempfile.TemporaryDirectory() as td:
        tmp = Path(td)
        d_letter, transform = trace(crop(letter), tmp, "letter")
        d_arrow, _ = trace(crop(arrow), tmp, "arrow")

    OUT_TS.write_text(f'''/**
 * The New Manager Success mark, as vector path data.
 *
 * AUTO-GENERATED by packages/brand/scripts/trace-mark.py — do not hand-edit.
 *
 * This is a **trace of the real artwork**, not an interpretation. The supplied
 * brush-painted PNG (packages/brand/assets/source/mark.png) was split into its
 * white and blue channels and vectorised with potrace, so the dry-brush
 * texture and tapered stroke ends are the designer's, not an approximation.
 *
 * Both the web and native components import from here, so the geometry has
 * exactly one definition and cannot drift.
 */

/** Natural dimensions of the traced artwork. */
export const markViewBox = {{ width: {width}, height: {height} }} as const;

/**
 * potrace emits paths in tenth-units with a flipped Y axis; this transform
 * puts them back into the viewBox above. Apply it to a <g> wrapping both paths.
 */
export const markTransform = '{transform}';

/** The letterform. White on dark surfaces, ink on light ones. */
export const markLetterPath =
  '{d_letter}';

/** The arrow. Always the brand blue. */
export const markArrowPath =
  '{d_arrow}';
''')

    print(f"traced {SOURCE.name}: viewBox 0 0 {width} {height}")
    print(f"  letterform {len(d_letter)} chars, arrow {len(d_arrow)} chars")
    print(f"  wrote {OUT_TS.relative_to(BRAND.parent.parent)}")
    print(f"  sampled brand blue: {sampled_blue(rgb, arrow)}  "
          f"(compare BRAND_BLUE in src/color.ts)")
    print("\nNext: npm run build --workspace=@nms/brand"
          " && node packages/brand/scripts/gen-icons.mjs")


if __name__ == "__main__":
    main()
