import type { Metadata } from 'next';
import Link from 'next/link';
import {
  emptyProgress,
  applyActivity,
  recordQuizAttempt,
  sectionCompleteNotifications,
  weeklyDigestNotifications,
  inactivityNotifications,
  updateLevelSummary,
  type Enrollment,
  type Notification,
  type NotificationBlock,
} from '@nms/core';
import { module01 } from '@nms/content';
import styles from './corner.module.css';

export const metadata: Metadata = {
  title: 'What your Corner sees',
  description:
    'Exactly what a boss, HR contact, or mentor receives at each update level, rendered from the real notification engine, not a mockup.',
};

/**
 * Renders real output from `@nms/core` rather than a static mockup.
 *
 * This page is the sales conversation with an HR buyer, and the fastest way to
 * lose that conversation is to show a designed screenshot that the shipped
 * product does not match. Everything below is produced by the same functions
 * that will send the actual emails.
 */

const DEMO_ENROLLMENT: Enrollment = {
  id: 'demo',
  entry: 'other-individual',
  student: { name: 'Dana Reyes', email: 'dana@example.com' },
  registeredBy: { name: 'Sam Okafor', email: 'sam@example.com' },
  startedAt: new Date('2026-07-27T09:00:00Z'),
  contacts: [
    { id: 'c1', name: 'Lee Park', email: 'lee@example.com', role: 'boss', level: 1 },
    { id: 'c2', name: 'Jo Silva', email: 'jo@example.com', role: 'hr', level: 2 },
    { id: 'c3', name: 'Sam Okafor', email: 'sam@example.com', role: 'registrant', level: 3 },
  ],
};

function buildDemo() {
  const week = { start: new Date('2026-08-10T00:00:00Z'), end: new Date('2026-08-17T00:00:00Z') };
  let progress = emptyProgress('demo', DEMO_ENROLLMENT.startedAt);

  for (const [i, repId] of ['m1-r1', 'm1-r2', 'm1-r3'].entries()) {
    const at = new Date(`2026-08-1${1 + i}T10:00:00Z`);
    progress = applyActivity(progress, {
      id: `open-${repId}`,
      enrollmentId: 'demo',
      type: 'rep-opened',
      repId,
      at,
    });
    progress = applyActivity(progress, {
      id: `done-${repId}`,
      enrollmentId: 'demo',
      type: 'rep-completed',
      repId,
      at,
    });
  }

  // A perfect run on 1.1, a miss on 1.3 — a digest that is all green reads as
  // marketing. Buyers trust a report that can show a bad week.
  progress = recordQuizAttempt(
    progress,
    'm1-r1',
    module01.reps[0]!.quiz.map((q) => ({
      questionId: q.id,
      optionId: q.options.find((o) => o.correct)!.id,
    })),
    new Date('2026-08-11T10:20:00Z'),
  ).progress;

  progress = recordQuizAttempt(
    progress,
    'm1-r3',
    module01.reps[2]!.quiz.map((q, i) => ({
      questionId: q.id,
      optionId: (i === 0 ? q.options.find((o) => !o.correct) : q.options.find((o) => o.correct))!.id,
    })),
    new Date('2026-08-13T10:20:00Z'),
  ).progress;

  const level1 = sectionCompleteNotifications(DEMO_ENROLLMENT, 'm1-r3');

  const digests = weeklyDigestNotifications({
    enrollment: DEMO_ENROLLMENT,
    progress,
    weekStart: week.start,
    weekEnd: week.end,
    fieldNoteAnswers: [
      {
        repId: 'm1-r2',
        fieldNoteId: 'm1-r2-fn1',
        topic: 'The doer trap',
        text: 'I am still building the weekly client report myself. Priya could do it but the last version she sent had errors and I did not want to have that conversation.',
        savedAt: new Date('2026-08-12T11:00:00Z'),
      },
      {
        repId: 'm1-r3',
        fieldNoteId: 'm1-r3-fn1',
        topic: 'Relationship reset',
        text: 'Marcus and I used to complain about management together. Now I am management and he has basically stopped talking to me.',
        savedAt: new Date('2026-08-13T11:00:00Z'),
      },
    ],
  });

  const inactivity = inactivityNotifications({
    enrollment: DEMO_ENROLLMENT,
    lastActivityAt: new Date('2026-08-13T10:00:00Z'),
    now: new Date('2026-08-24T09:00:00Z'),
  });

  return {
    level1: level1[0]!,
    level2: digests.find((d) => d.to.level === 2)!,
    level3: digests.find((d) => d.to.level === 3)!,
    inactivity: inactivity.notifications[0]!,
    inactivityState: inactivity.state,
  };
}

export default function CornerPage() {
  const demo = buildDemo();

  return (
    <div className={`nms-shell ${styles.wrap}`}>
      <p className="nms-eyebrow">For managers of managers</p>
      <h1 className={styles.title}>Exactly what your Corner sees</h1>
      <p className={styles.lede}>
        Every message below is generated by the live notification engine using a sample learner —
        not a designed mockup. What ships is what you are looking at.
      </p>

      <section className={styles.section}>
        <h2 className={styles.h2}>Level 1: Basic</h2>
        <p className={styles.cadence}>{updateLevelSummary[1].cadence}</p>
        <p className={styles.body}>{updateLevelSummary[1].contents}</p>
        <MessageCard note={demo.level1} />
      </section>

      <section className={styles.section}>
        <h2 className={styles.h2}>Level 2: Intermediate</h2>
        <p className={styles.cadence}>{updateLevelSummary[2].cadence}</p>
        <p className={styles.body}>{updateLevelSummary[2].contents}</p>
        <MessageCard note={demo.level2} />
      </section>

      <section className={styles.section}>
        <h2 className={styles.h2}>Level 3: Advanced</h2>
        <p className={styles.cadence}>{updateLevelSummary[3].cadence}</p>
        <p className={styles.body}>{updateLevelSummary[3].contents}</p>
        <MessageCard note={demo.level3} />

        <div className={styles.privacyNote}>
          <h3>Why you get questions and not answers</h3>
          <p>
            Module 1 asks learners to write down which working relationship has soured and which
            standard they are failing to hold themselves to. If their boss can read that verbatim,
            they will work out within one module that honest answers are career-limiting, and start
            writing for the audience.
          </p>
          <p>
            So the reflections stay private and you receive conversation prompts built from them.
            Generation is capped at four-word phrases and enforced by a test that no longer verbatim
            span can survive.
          </p>
        </div>
      </section>

      <section className={styles.section}>
        <h2 className={styles.h2}>The safety net: every contact, every level</h2>
        <p className={styles.body}>
          If a learner goes quiet for 7 business days, everyone in their Corner hears about it —
          including Level 2 and Level 3 contacts who would otherwise only get a weekly digest. It
          repeats every 7 business days until they pick it back up. Any activity resets the clock,
          including just opening a section.
        </p>
        <MessageCard note={demo.inactivity} />
      </section>

      <div className={styles.cta}>
        <Link href="/enroll" className="nms-btn nms-btn--bright">
          Enroll a team
        </Link>
        <Link href="/for-teams" className="nms-btn nms-btn--ghost">
          How it works for teams
        </Link>
      </div>
    </div>
  );
}

function MessageCard({ note }: { note: Notification }) {
  return (
    <article className={styles.message} data-kind={note.kind}>
      <header className={styles.messageHead}>
        <span className={styles.to}>
          To: {note.to.name} <span className={styles.email}>&lt;{note.to.email}&gt;</span>
        </span>
        <span className={styles.kind}>
          {note.kind === 'inactivity-alert' ? 'Alert' : `Level ${note.to.level}`}
        </span>
      </header>
      <p className={styles.subject}>{note.subject}</p>
      <div className={styles.blocks}>
        {note.body.map((block, i) => (
          <Block key={i} block={block} />
        ))}
      </div>
    </article>
  );
}

function Block({ block }: { block: NotificationBlock }) {
  switch (block.type) {
    case 'paragraph':
      return <p className={styles.para}>{block.text}</p>;
    case 'stat':
      return (
        <p className={styles.stat}>
          <span>{block.label}</span>
          <strong>{block.value}</strong>
        </p>
      );
    case 'list':
      return (
        <div className={styles.list}>
          <p className={styles.listTitle}>{block.title}</p>
          <ul>
            {block.items.map((item, i) => (
              <li key={i}>{item}</li>
            ))}
          </ul>
        </div>
      );
    case 'questions':
      return (
        <div className={styles.questions}>
          <p className={styles.listTitle}>{block.title}</p>
          <ol>
            {block.questions.map((q, i) => (
              <li key={i}>
                <span className={styles.question}>{q.question}</span>
                <span className={styles.rationale}>{q.rationale}</span>
              </li>
            ))}
          </ol>
        </div>
      );
    case 'note':
      return <p className={styles.noteBlock}>{block.text}</p>;
  }
}
